In [1]:
# IPython, the interactive python shell used by the Notebook, has a set of predefined ‘magic functions'
# that you can call with a command line style syntax.
# The following one is for asking the plotting library to draw inside the notebook, instead of on a separate window.
# this line above prepares the jupyter notebook for working with matplotlib

%matplotlib inline 

# Below is the set of most useful data science modules that you will need for your code
# See all the "as ..." contructs? They're just aliasing the package names.
# That way we can call methods like plt.plot() instead of matplotlib.pyplot.plot().
# notice we use short aliases here, and these are conventional in the python community

import numpy as np               # imports a fast numerical programming library
import scipy as sp               # imports stats functions, amongst other things
import matplotlib as mpl         # this actually imports matplotlib
import matplotlib.cm as cm       # allows us easy access to colormaps
import matplotlib.pyplot as plt  # sets up plotting under plt
import pandas as pd              #lets us handle data as dataframes

# sets up pandas table display
pd.set_option('display.width', 500)
pd.set_option('display.max_columns', 100)
pd.set_option('display.notebook_repr_html', True)

import seaborn as sns            # sets up styles and gives us more plotting options
from bs4 import BeautifulSoup    # imports web parsing library https://www.crummy.com/software/BeautifulSoup/


In [2]:
"""
Function
--------
simulate_prizedoor

Generate a random array of 0s, 1s, and 2s, representing
hiding a prize between door 0, door 1, and door 2

Parameters
----------
nsim : int
    The number of simulations to run

Returns
-------
sims : array
    Random array of 0s, 1s, and 2s

Example
-------
>>> print simulate_prizedoor(3)
array([0, 0, 2])
"""

def simulate_prizedoor(nsim):
    return np.random.randint(0, 3, (nsim))


In [4]:
print (simulate_prizedoor(100))

[1 0 0 1 2 1 2 2 1 2 0 1 0 0 0 0 0 0 0 2 2 1 2 0 1 2 1 0 0 2 2 0 2 1 0 2 0
 1 1 2 1 2 1 2 0 2 1 0 2 1 0 2 1 2 2 1 1 0 0 1 2 2 2 0 1 0 1 1 2 1 0 0 1 0
 0 2 2 1 1 2 0 1 1 2 2 1 0 0 0 2 0 1 2 2 1 1 1 2 0 0]


In [5]:
"""
Function
--------
simulate_guess

Return any strategy for guessing which door a prize is behind. This
could be a random strategy, one that always guesses 2, whatever.

Parameters
----------
nsim : int
    The number of simulations to generate guesses for

Returns
-------
guesses : array
    An array of guesses. Each guess is a 0, 1, or 2

Example
-------
>>> print simulate_guess(5)
array([0, 0, 0, 0, 0])
"""

def simulate_guess(nsim):
    return np.zeros(nsim, dtype=np.int)

In [6]:
print (simulate_guess(100))

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [7]:
print (np.random.randint(5, 10, 100))

[6 6 5 9 5 5 7 6 5 5 7 7 5 6 9 5 6 5 9 7 9 6 8 9 8 6 9 5 5 6 5 8 7 7 8 5 8
 9 7 8 8 9 9 9 7 7 6 5 8 6 5 5 6 8 5 6 5 7 9 5 9 6 9 7 8 8 9 6 5 7 7 8 6 9
 7 5 8 5 7 5 5 8 5 6 9 8 5 6 5 8 5 5 7 7 6 5 9 9 6 9]


In [8]:
"""
Function
--------
goat_door

Simulate the opening of a "goat door" that doesn't contain the prize,
and is different from the contestants guess

Parameters
----------
prizedoors : array
    The door that the prize is behind in each simulation
guesses : array
    THe door that the contestant guessed in each simulation

Returns
-------
goats : array
    The goat door that is opened for each simulation. Each item is 0, 1, or 2, and is different
    from both prizedoors and guesses

Examples
--------
>>> print goat_door(np.array([0, 1, 2]), np.array([1, 1, 1]))
>>> array([2, 2, 0])
"""

def goat_door(prizedoors, guesses):
    
    # strategy: generate random answers, and
    # keep updating until they satisfy the rule
    # that they aren't a prizedoor or a guess
    result = np.random.randint(0, 3, prizedoors.size)
    while True:
        bad = (result == prizedoors) | (result == guesses)
        if not bad.any():
            return result
        result[bad] = np.random.randint(0, 3, bad.sum())

In [9]:
 print goat_door(np.array([0, 1, 2]), np.array([1, 1, 1]))

SyntaxError: invalid syntax (<ipython-input-9-6171fb27d3c0>, line 1)

In [10]:
 print (goat_door(np.array([0, 1, 2]), np.array([1, 1, 1])))

[2 2 0]


In [11]:
 print (goat_door(np.array([0, 1, 2]), np.array([1, 1, 1])))

[2 2 0]


In [12]:
 print (goat_door(np.array([0, 1, 0]), np.array([1, 1, 1])))

[2 0 2]


In [13]:
"""
Function
--------
switch_guess

The strategy that always switches a guess after the goat door is opened

Parameters
----------
guesses : array
     Array of original guesses, for each simulation
goatdoors : array
     Array of revealed goat doors for each simulation

Returns
-------
The new door after switching. Should be different from both guesses and goatdoors

Examples
--------
>>> print switch_guess(np.array([0, 1, 2]), np.array([1, 2, 1]))
>>> array([2, 0, 0])
"""

def switch_guess(guesses, goatdoors):
    result = np.zeros(guesses.size)
    switch = {(0, 1): 2, (0, 2): 1, (1, 0): 2, (1, 2): 1, (2, 0): 1, (2, 1): 0}
    for i in [0, 1, 2]:
        for j in [0, 1, 2]:
            mask = (guesses == i) & (goatdoors == j)
            if not mask.any():
                continue
            result = np.where(mask, np.ones_like(result) * switch[(i, j)], result)
    return result

In [14]:
"""
Function
--------
win_percentage

Calculate the percent of times that a simulation of guesses is correct

Parameters
-----------
guesses : array
    Guesses for each simulation
prizedoors : array
    Location of prize for each simulation

Returns
--------
percentage : number between 0 and 100
    The win percentage

Examples
---------
>>> print win_percentage(np.array([0, 1, 2]), np.array([0, 0, 0]))
33.333
"""

def win_percentage(guesses, prizedoors):
    return 100 * (guesses == prizedoors).mean()

In [15]:
nsim = 10000

# keep guesses
print("Win percentage when keeping original door")
print(win_percentage(simulate_prizedoor(nsim), simulate_guess(nsim)))

#switch
pd = simulate_prizedoor(nsim)
guess = simulate_guess(nsim)
goats = goat_door(pd, guess)
guess = switch_guess(guess, goats)
print("Win percentage when switching doors")
print(win_percentage(pd, guess).mean())

Win percentage when keeping original door
33.0
Win percentage when switching doors
66.84


In [16]:
nsim = 100

# keep guesses
print("Win percentage when keeping original door")
print(win_percentage(simulate_prizedoor(nsim), simulate_guess(nsim)))

#switch
pd = simulate_prizedoor(nsim)
guess = simulate_guess(nsim)
goats = goat_door(pd, guess)
guess = switch_guess(guess, goats)
print("Win percentage when switching doors")
print(win_percentage(pd, guess).mean())

Win percentage when keeping original door
30.0
Win percentage when switching doors
68.0


In [17]:
nsim = 10000000

# keep guesses
print("Win percentage when keeping original door")
print(win_percentage(simulate_prizedoor(nsim), simulate_guess(nsim)))

#switch
pd = simulate_prizedoor(nsim)
guess = simulate_guess(nsim)
goats = goat_door(pd, guess)
guess = switch_guess(guess, goats)
print("Win percentage when switching doors")
print(win_percentage(pd, guess).mean())

Win percentage when keeping original door
33.33583
Win percentage when switching doors
66.66805


In [18]:
[0, 1, 2].size

AttributeError: 'list' object has no attribute 'size'

In [19]:
np.array([0, 1, 2]).size

3

In [20]:
"""
Function
--------
switch_guess

The strategy that always switches a guess after the goat door is opened

Parameters
----------
guesses : array
     Array of original guesses, for each simulation
goatdoors : array
     Array of revealed goat doors for each simulation

Returns
-------
The new door after switching. Should be different from both guesses and goatdoors

Examples
--------
>>> print switch_guess(np.array([0, 1, 2]), np.array([1, 2, 1]))
>>> array([2, 0, 0])
"""

def switch_guess(guesses, goatdoors):
    result = np.zeros(guesses.size)
    switch = {(0, 1): 2, (0, 2): 1, (1, 0): 2, (1, 2): 1, (2, 0): 1, (2, 1): 0}
    for i in [0, 1, 2]:
        for j in [0, 1, 2]:
            mask = (guesses == i) & (goatdoors == j)
            if not mask.any():
                continue
            result = np.where(mask, np.ones_like(result) * switch[(i, j)], result)
    return result

In [21]:
"""
Function
--------
goat_door

Simulate the opening of a "goat door" that doesn't contain the prize,
and is different from the contestants guess

Parameters
----------
prizedoors : array
    The door that the prize is behind in each simulation
guesses : array
    THe door that the contestant guessed in each simulation

Returns
-------
goats : array
    The goat door that is opened for each simulation. Each item is 0, 1, or 2, and is different
    from both prizedoors and guesses

Examples
--------
>>> print goat_door(np.array([0, 1, 2]), np.array([1, 1, 1]))
>>> array([2, 2, 0])
"""

def goat_door(prizedoors, guesses):
    
    # strategy: generate random answers, and
    # keep updating until they satisfy the rule
    # that they aren't a prizedoor or a guess
    result = np.random.randint(0, 3, prizedoors.size)
    while True:
        bad = (result == prizedoors) | (result == guesses)
        if not bad.any():
            return result
        result[bad] = np.random.randint(0, 3, bad.sum())

In [22]:
prizedoors=np.array([0, 1, 2])
guesses=np.array([1, 1, 1])

In [23]:
result = np.random.randint(0, 3, prizedoors.size)

In [24]:
result

array([1, 0, 1])

In [25]:
bad = (result == prizedoors) | (result == guesses)
bad

array([ True, False,  True], dtype=bool)

In [26]:
bad = (result == prizedoors) or (result == guesses)
bad

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [27]:
bad = (result == prizedoors) & (result == guesses)
bad

array([False, False, False], dtype=bool)

In [28]:
bad = (result == prizedoors) | (result == guesses)
bad
bad.any()

True

In [29]:
bad = (result == prizedoors) | (result == guesses)
bad.any()

True

In [30]:
bad = (result == prizedoors) | (result == guesses)
bad.all()

False

In [31]:
bad = (result == prizedoors) | (result == guesses)
bad

array([ True, False,  True], dtype=bool)

In [32]:
 result[bad] 

array([1, 1])

In [33]:
bad.sum()

2

In [34]:
"""
Function
--------
switch_guess

The strategy that always switches a guess after the goat door is opened

Parameters
----------
guesses : array
     Array of original guesses, for each simulation
goatdoors : array
     Array of revealed goat doors for each simulation

Returns
-------
The new door after switching. Should be different from both guesses and goatdoors

Examples
--------
>>> print switch_guess(np.array([0, 1, 2]), np.array([1, 2, 1]))
>>> array([2, 0, 0])
"""

def switch_guess(guesses, goatdoors):
    result = np.zeros(guesses.size)
    switch = {(0, 1): 2, (0, 2): 1, (1, 0): 2, (1, 2): 1, (2, 0): 1, (2, 1): 0}
    for i in [0, 1, 2]:
        for j in [0, 1, 2]:
            mask = (guesses == i) & (goatdoors == j)
            if not mask.any():
                continue
            result = np.where(mask, np.ones_like(result) * switch[(i, j)], result)
    return result

In [35]:
 print switch_guess(np.array([0, 1, 2]), np.array([1, 2, 1]))

SyntaxError: invalid syntax (<ipython-input-35-23a7da9851c2>, line 1)

In [36]:
 print (switch_guess(np.array([0, 1, 2]), np.array([1, 2, 1])))

[ 2.  1.  0.]
